stages:
  load_save_data:
    cmd: python src/stage_01_load_save.py
    deps:
      - src/stage_01_load_save.py
      - src/utils/all_utils.py
      - config/config.yaml
    outs:
      - artifacts/raw_data/raw_data.csv

  split_data:
    cmd: python src/stage_02_split_data.py
    deps:
      - src/stage_02_split_data.py
      - src/utils/all_utils.py
      - config/config.yaml
      - params.yaml
    params:
      - base.test_size
      - base.random_state
    outs:
      - artifacts/splitted_data/test.csv
      - artifacts/splitted_data/train.csv

  train_model:
    cmd: python src/stage_03_train.py
    deps:
      - src/stage_03_train.py
      - src/utils/all_utils.py
      - config/config.yaml
      - params.yaml
    params:
      - model_params.alpha
      - model_params.l1_ratio
    outs:
      - artifacts/model/elasticnet.model
  
  eval_model:
    cmd: python src/stage_04_evaluate.py
    deps:
      - src/stage_04_evaluate.py
      - src/utils/all_utils.py
      - config/config.yaml
      - params.yaml
    outs:
      - artifacts/results.json